#!/bin/bash

sleep 3

service mariadb start
echo "CREATE DATABASE IF NOT EXISTS $WP_DB_NAME; CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD'; GRANT ALL PRIVILEGES ON $WP_DB_NAME.* TO '$DB_USER'@'%'; FLUSH PRIVILEGES;" \
 | mariadb -u root

